# Generated by Django 4.2 on 2025-05-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuari',
            name='contrasenya',
            field=models.CharField(max_length=128),
        ),
    ]
